apiVersion: gcp.platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: configuration-gcp-database-mysql
  namespace: default
spec:
  parameters:
    engine: mysql
    engineVersion: "8_0"
    region: us-west2
    storageGB: 10
    passwordSecretRef:
      namespace: default
      name: mysqlsecret
      key: password
    networkRef:
      id: configuration-gcp-database
  writeConnectionSecretToRef:
    name: configuration-gcp-database-mysql-conn
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mysqlsecret
  namespace: default
type: Opaque
