apiVersion: gcp.platform.upbound.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: configuration-gcp-database
  namespace: default
spec:
  parameters:
    storageGB: 10
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    networkRef:
      id: configuration-gcp-database
  writeConnectionSecretToRef:
    name: configuration-gcp-database-conn
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque
