apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqlinstances.gcp.platform.upbound.io
spec:
  group: gcp.platform.upbound.io
  names:
    kind: XPostgreSQLInstance
    plural: xpostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - privateIP
    - serverCACertificateCert
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    storageGB:
                      type: integer
                    passwordSecretRef:
                      type: object
                      description: "A reference to the Secret object containing database password"
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                        key:
                          type: string
                      required:
                        - namespace
                        - name
                        - key
                    networkRef:
                      type: object
                      description: "A reference to the Network object that this postgres should be
                      connected to."
                      properties:
                        id:
                          type: string
                          description: ID of the Network object this ref points to.
                      required:
                        - id
                  required:
                    - storageGB
                    - networkRef
                    - passwordSecretRef
              required:
                - parameters
